[chore] reorganize build checks - allow to execute on GH merge queues (#3091)
* [chore] reorganize build checks

* allow to execute checks on GH merge queues

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -3,6 +3,8 @@
 name: Checks
 
 on:
+  merge_group:
+    types: [checks_requested]
   push:
     branches: [main]
   pull_request:
@@ -81,3 +83,29 @@ jobs:
         uses: actions/checkout@v6.0.2
       - name: run checklicense
         run: make checklicense
+
+  build-test:
+    needs: [
+      build_images,
+      markdownlint,
+      yamllint,
+      misspell,
+      checklinks,
+      sanity,
+      checklicense
+    ]
+    if: always() && !cancelled()
+    runs-on: ubuntu-latest
+    steps:
+      - name: Report CI status
+        shell: bash
+        env:
+          CI_SUCCESS: ${{ !contains(needs.*.result, 'failure') }}
+        run: |
+          if [ "${CI_SUCCESS}" == "true" ]
+          then
+            echo 'Build complete ✓'
+          else
+            echo 'Build failed ✗'
+            exit 1
+          fi
